### PR TITLE
For TTL, 60 seconds seems a bit frequent

### PR DESCRIPTION
**Pull request by chappjc**
10 minutes might me a bit more considerate of the nodes, or at least their logs

### CODE REVIEW

**Comment by chappjc** [comment]
Refer: https://github.com/decred/decred-seeder/pull/1#issuecomment-199252531

**Comment by jcvernaleo** [comment]
@dajohi do you have any opinion on this?

**Comment by dajohi** [comment]
@chappjc can you provide a better reason for this change?   I can provide a reason against:  The higher the TTL the more chance of serving stale IPs (hosts that are down).

**Comment by chappjc** [comment]
@dajohi Nope.  There was a stink about getting banned in a related PR upstream: https://github.com/sipa/bitcoin-seeder/pull/31.  There was no evidence there and I don't have any.  I just didn't think it was necessary to pester nodes this frequently.  I'm happy to make edits for my own purposes.

**Pull request closed without merging**
