### PR TITLE
Allow to override default compiler using the ?= syntax.

### PR DESCRIPTION
**Pull request by chappjc**

### CODE REVIEW

**Comment by chappjc** [comment]
Ref: https://github.com/decred/decred-seeder/pull/1#issuecomment-199252531

**Comment by jcvernaleo** [comment]
Looks good.
OK

**Comment by jcvernaleo** [comment]
Actually, could you rebase this on master so I can fast-forward merge it?  Once you do that I'll get it in.

**Comment by chappjc** [comment]
Hmm, I didn't see your merge, but I did rebase 3 (this) onto master, and 5 onto this.  Pretty sure I messed up something, but it looks OK on my end.

**Pull request merged**
