### PR TITLE
Sync with upstream

### PR DESCRIPTION
**Pull request by jrick**

### CODE REVIEW

**Review by jcvernaleo — APPROVED** [review]
I tested this on my testnet seeder on debian and it seems all good to me.

OK

**Comment by jcvernaleo** [comment]
@dajohi do you have any reason for this not to go in?

**Comment by jrick** [comment]
Made a new merge commit over the latest master.  I made some modifications to the Makefile to closer match upstream so that could use another look.

**Comment by jcvernaleo** [comment]
New merge commit looks good to me and it seems to be working fine on my testnet seeder.
OK

**Review by dajohi — APPROVED** [review]
ok

**Pull request merged**
